[build]
	command = "# no build command"
	functions = "functions"
	publish = "public"

[build.environment]
	NODE_VERSION = "20"

[functions]
    node_bundler = "esbuild"
    included_files = ["functions/cats/*.jpg"]
